"""car_product source column added

Revision ID: 05369d69aa55
Revises: 44c5d3815132
Create Date: 2020-09-14 05:01:04.257716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "05369d69aa55"
down_revision = "44c5d3815132"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weedmaps_product")
    op.drop_table("car_product")
    op.drop_table("weedmaps_shop")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weedmaps_shop",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "weedmaps_id",
            sa.VARCHAR(length=25),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "business_name", sa.TEXT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "type", sa.VARCHAR(length=25), autoincrement=False, nullable=False
        ),
        sa.Column(
            "category",
            sa.VARCHAR(length=25),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("city", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("web_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("slug", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("aboutus", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "amenities",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "announcement", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "business_hours",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("email", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "f_t_announcement", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("intro", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("services", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("website", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="weedmaps_shop_pkey"),
        sa.UniqueConstraint(
            "weedmaps_id", name="weedmaps_shop_weedmaps_id_key"
        ),
    )
    op.create_table(
        "car_product",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "product_name", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("price", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "images",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("make", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("model", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("year", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("body_style", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("odometer", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "transmission", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("engine", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("engine_size", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("driveline", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "exterior_color", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "interior_color", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("doors", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("passengers", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fuel", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("city_fuel", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("hwy_fuel", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "stock_number", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("vin", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("details", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "options",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("web_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="car_product_pkey"),
    )
    op.create_table(
        "weedmaps_product",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "weedmaps_id",
            sa.VARCHAR(length=25),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("shop_slug", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "category",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("image_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "short_description", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "prices",
            postgresql.ARRAY(sa.VARCHAR(length=25)),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "prices_labels",
            postgresql.ARRAY(sa.VARCHAR(length=25)),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "price_unit",
            sa.VARCHAR(length=25),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "strain_effects",
            postgresql.ARRAY(sa.VARCHAR(length=25)),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "strain_flavours",
            postgresql.ARRAY(sa.VARCHAR(length=25)),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("web_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "details_collected",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="weedmaps_product_pkey"),
    )
    # ### end Alembic commands ###
