"""cars engine_cylinders

Revision ID: 0cb728ab197d
Revises: 9e01343b62ef
Create Date: 2020-10-19 07:43:01.785933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb728ab197d'
down_revision = '9e01343b62ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_product', sa.Column('engine_cylinders', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_product', 'engine_cylinders')
    # ### end Alembic commands ###
