"""WM_product details_collected column added

Revision ID: 1572a0239a78
Revises: 
Create Date: 2020-09-09 07:48:47.704328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1572a0239a78"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weedmaps_product",
        sa.Column("details_collected", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("weedmaps_product", "details_collected")
    # ### end Alembic commands ###
