"""R2GBusiness target_link link added

Revision ID: 16f137a42bdb
Revises: e0f21f36a2a0
Create Date: 2021-03-04 09:01:53.300715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f137a42bdb'
down_revision = 'e0f21f36a2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('r2_g_business', sa.Column('target_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('r2_g_business', 'target_link')
    # ### end Alembic commands ###
