"""user model added

Revision ID: 172fb3a90b3b
Revises: b12bc04bb03d
Create Date: 2020-10-16 05:43:50.836987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '172fb3a90b3b'
down_revision = 'b12bc04bb03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permissions', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('user', sa.Column('role', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('user', 'permissions')
    # ### end Alembic commands ###
