"""coordinates column added

Revision ID: 335ad9825bf5
Revises: cb2613ae9f03
Create Date: 2020-10-08 06:02:44.414627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "335ad9825bf5"
down_revision = "cb2613ae9f03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gmaps_business", sa.Column("coordinates", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gmaps_business", "coordinates")
    # ### end Alembic commands ###
