"""car_product status added

Revision ID: 3b4bf3f4aeda
Revises: 108b2c429634
Create Date: 2020-09-30 03:31:31.769984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b4bf3f4aeda"
down_revision = "108b2c429634"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("car_product", sa.Column("status", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("car_product", "status")
    # ### end Alembic commands ###
