"""gmaps_id column added

Revision ID: 4032ce193e06
Revises: 3b4bf3f4aeda
Create Date: 2020-10-08 05:09:20.703333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4032ce193e06"
down_revision = "3b4bf3f4aeda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gmaps_business", sa.Column("gmaps_id", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gmaps_business", "gmaps_id")
    # ### end Alembic commands ###
