"""R2GBusiness and BUSINESS inst added

Revision ID: 6336062588dc
Revises: 16f137a42bdb
Create Date: 2021-03-05 14:34:54.576967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6336062588dc'
down_revision = '16f137a42bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('soc_ig', sa.Text(), nullable=True))
    op.add_column('r2_g_business', sa.Column('soc_ig', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('r2_g_business', 'soc_ig')
    op.drop_column('business', 'soc_ig')
    # ### end Alembic commands ###
