"""BUSINESS source_name__id added

Revision ID: 8cbc2e609699
Revises: 6336062588dc
Create Date: 2021-03-10 08:05:50.272540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbc2e609699'
down_revision = '6336062588dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('source_name__id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'source_name__id')
    # ### end Alembic commands ###
