"""common add content,

Revision ID: 920ac7659cb4
Revises: 05369d69aa55
Create Date: 2020-09-15 07:44:34.730807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "920ac7659cb4"
down_revision = "05369d69aa55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "car_product", sa.Column("condition", sa.Text(), nullable=True)
    )
    op.add_column("car_product", sa.Column("content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("car_product", "content")
    op.drop_column("car_product", "condition")
    # ### end Alembic commands ###
