"""cars added fields

Revision ID: 9e01343b62ef
Revises: 172fb3a90b3b
Create Date: 2020-10-19 07:41:26.893114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e01343b62ef'
down_revision = '172fb3a90b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_product', sa.Column('trim', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_product', 'trim')
    # ### end Alembic commands ###
