"""categoty column added

Revision ID: a0473b654f4d
Revises: 4032ce193e06
Create Date: 2020-10-08 05:27:19.406086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0473b654f4d"
down_revision = "4032ce193e06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gmaps_business", sa.Column("category", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gmaps_business", "category")
    # ### end Alembic commands ###
