"""project fiela added to gmaps

Revision ID: a804ef5bd612
Revises: 9c1f33939bca
Create Date: 2020-10-12 06:36:29.803813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a804ef5bd612"
down_revision = "9c1f33939bca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gmaps_business", sa.Column("project", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gmaps_business", "project")
    # ### end Alembic commands ###
