"""R2BUSINESS target_id added

Revision ID: aa4439dc4c1a
Revises: 8cbc2e609699
Create Date: 2021-03-15 07:25:26.939528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4439dc4c1a'
down_revision = '8cbc2e609699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('r2_g_business', sa.Column('target_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('r2_g_business', 'target_id')
    # ### end Alembic commands ###
