"""BUSINESS mapping fileds added

Revision ID: ac478543285e
Revises: 58e567ebb762
Create Date: 2021-01-26 06:18:54.072877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac478543285e'
down_revision = '58e567ebb762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('mapped', sa.Boolean(), nullable=True))
    op.add_column('business', sa.Column('order_in_mapping_queue', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'order_in_mapping_queue')
    op.drop_column('business', 'mapped')
    # ### end Alembic commands ###
