"""BUSINESS bool skipped added

Revision ID: af048f6cc3c5
Revises: 3cc829bbdf55
Create Date: 2021-02-16 05:01:35.810554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af048f6cc3c5'
down_revision = '3cc829bbdf55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('skipped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'skipped')
    # ### end Alembic commands ###
