"""order in queue weedmaps, gmaps

Revision ID: b12bc04bb03d
Revises: cbc66ef6bed8
Create Date: 2020-10-14 05:32:03.353411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12bc04bb03d'
down_revision = 'cbc66ef6bed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmaps_business', sa.Column('order_in_mapping_queue', sa.Integer(), nullable=True))
    op.add_column('weedmaps_shop', sa.Column('order_in_mapping_queue', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weedmaps_shop', 'order_in_mapping_queue')
    op.drop_column('gmaps_business', 'order_in_mapping_queue')
    # ### end Alembic commands ###
