"""user update

Revision ID: c26ee9944151
Revises: ceffc7b4daed
Create Date: 2020-11-02 03:46:15.404331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26ee9944151'
down_revision = 'ceffc7b4daed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
