"""categoty column deleted, search_query column added

Revision ID: cb2613ae9f03
Revises: a0473b654f4d
Create Date: 2020-10-08 05:28:13.943792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb2613ae9f03"
down_revision = "a0473b654f4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gmaps_business", sa.Column("search_query", sa.Text(), nullable=True)
    )
    op.drop_column("gmaps_business", "category")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gmaps_business",
        sa.Column("category", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("gmaps_business", "search_query")
    # ### end Alembic commands ###
