"""weed mapping table

Revision ID: cbc66ef6bed8
Revises: a804ef5bd612
Create Date: 2020-10-14 05:04:37.082379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cbc66ef6bed8"
down_revision = "a804ef5bd612"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weed_mapping", sa.Column("weedmaps_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "weed_mapping", "weedmaps_shop", ["weedmaps_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "weed_mapping", type_="foreignkey")
    op.drop_column("weed_mapping", "weedmaps_id")
    # ### end Alembic commands ###
