"""cars airbags

Revision ID: ceffc7b4daed
Revises: c317ffbb80bf
Create Date: 2020-10-19 08:26:54.597824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceffc7b4daed'
down_revision = 'c317ffbb80bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_product', sa.Column('airbags', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_product', 'airbags')
    # ### end Alembic commands ###
