"""R2GBUSINESS logo added

Revision ID: e0f21f36a2a0
Revises: af048f6cc3c5
Create Date: 2021-02-25 04:23:50.578094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f21f36a2a0'
down_revision = 'af048f6cc3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('r2_g_business', sa.Column('logo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('r2_g_business', 'logo')
    # ### end Alembic commands ###
