"""

Revision ID: eb4264685aa0
Revises: b472ee8af14a
Create Date: 2020-11-12 05:43:28.432304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4264685aa0'
down_revision = 'b472ee8af14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_product', sa.Column('car_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_product', 'car_id')
    # ### end Alembic commands ###
